-- Yamin Space: локализация латиницы в контенте Supabase
-- 1) Перезаписывает вопросы академии (quiz 4–6) — выполни seed-academy.sql
-- 2) Переводит Kelly-слова с английского translation_ru на русский

-- === Шаг 1: вопросы академии ===
-- Скопируй и выполни содержимое supabase/seed-academy.sql целиком,
-- либо выполни этот файл после него.

-- === Шаг 2: Kelly / частотные слова ===
UPDATE public.arabic_words AS w SET translation_ru = m.ru
FROM (VALUES
  ('through', 'Через'),
  ('building', 'Здание'),
  ('was considered', 'Считался'),
  ('maybe', 'Может быть'),
  ('global', 'Глобальный'),
  ('came', 'Пришёл'),
  ('education', 'Образование'),
  ('confirm', 'Подтверждать'),
  ('value', 'Ценность'),
  ('million', 'Миллион'),
  ('Arab', 'Араб'),
  ('percentage', 'Процент'),
  ('social', 'Социальный'),
  ('language', 'Язык'),
  ('transport', 'Транспорт'),
  ('gold', 'Золото'),
  ('text', 'Текст'),
  ('third', 'Третий'),
  ('source', 'Источник'),
  ('economic', 'Экономический'),
  ('working', 'Рабочий'),
  ('contract', 'Контракт'),
  ('free', 'Свободный'),
  ('relative to', 'Относительно'),
  ('full', 'Полный'),
  ('nation', 'Нация'),
  ('participation', 'Участие'),
  ('market', 'Рынок'),
  ('kill', 'Убивать'),
  ('ministry', 'Министерство'),
  ('organization', 'Организация'),
  ('past', 'Прошлое'),
  ('election', 'Выборы'),
  ('material', 'Материал'),
  ('stage', 'Этап'),
  ('turned', 'Достиг'),
  ('prayer', 'Молитва'),
  ('personal', 'Личный'),
  ('statement', 'Заявление'),
  ('emerged', 'Вышел'),
  ('basis', 'Основа'),
  ('sound', 'Звук'),
  ('citizen', 'Гражданин'),
  ('party', 'Сторона'),
  ('institution', 'Учреждение'),
  ('device', 'Устройство'),
  ('section', 'Раздел'),
  ('price', 'Цена'),
  ('agreement', 'Соглашение'),
  ('exist', 'Существовать'),
  ('hair', 'Волосы'),
  ('boy', 'Мальчик'),
  ('already', 'Уже'),
  ('policy', 'Политика'),
  ('line', 'Линия'),
  ('sector', 'Сектор'),
  ('sign', 'Подписать'),
  ('publish', 'Публиковать'),
  ('lead', 'Вести'),
  ('issue', 'Вопрос'),
  ('amount', 'Количество'),
  ('news', 'Новости'),
  ('service', 'Служба'),
  ('female', 'Женщины'),
  ('best', 'Лучший'),
  ('military', 'Военный'),
  ('king', 'Король'),
  ('adding', 'Добавление'),
  ('chest', 'Грудь'),
  ('many', 'Много'),
  ('page', 'Страница'),
  ('former', 'Бывший'),
  ('message', 'Сообщение'),
  ('position', 'Позиция'),
  ('strong', 'Сильный'),
  ('current', 'Текущий'),
  ('head', 'Голова'),
  ('great', 'Великий'),
  ('noted', 'Отметил'),
  ('level', 'Уровень'),
  ('end', 'Конец'),
  ('hearing', 'Слух'),
  ('understanding', 'Понимание'),
  ('spirit', 'Дух'),
  ('five', 'Пять'),
  ('story', 'История'),
  ('increase', 'Увеличение'),
  ('create', 'Создавать'),
  ('capacity', 'Способность'),
  ('newspaper', 'Газета'),
  ('team', 'Команда'),
  ('union', 'Союз'),
  ('pay', 'Платить'),
  ('way', 'Способ'),
  ('support', 'Поддержка'),
  ('beginning', 'Начало'),
  ('still', 'Всё ещё'),
  ('seem', 'Казаться'),
  ('individual', 'Индивид'),
  ('deputy', 'Заместитель'),
  ('myself', 'Сам'),
  ('report', 'Отчёт'),
  ('army', 'Армия'),
  ('scientific', 'Научный'),
  ('scientist', 'Учёный'),
  ('occur', 'Происходить'),
  ('little', 'Мало'),
  ('more', 'Больше'),
  ('group', 'Группа'),
  ('film', 'Фильм'),
  ('novel', 'Роман'),
  ('base', 'База'),
  ('clear', 'Ясный'),
  ('possible', 'Возможный'),
  ('address', 'Адрес'),
  ('under', 'Под'),
  ('opportunity', 'Возможность'),
  ('dialogue', 'Диалог'),
  ('unit', 'Единица'),
  ('disease', 'Болезнь'),
  ('where', 'Где'),
  ('dollar', 'Доллар'),
  ('raise', 'Поднимать'),
  ('doing', 'Делать'),
  ('age', 'Возраст'),
  ('entry', 'Вход'),
  ('answer', 'Ответ'),
  ('of course', 'Конечно'),
  ('four', 'Четыре'),
  ('interest', 'Интерес'),
  ('university', 'Университет'),
  ('professor', 'Профессор'),
  ('sentence', 'Предложение'),
  ('culture', 'Культура'),
  ('assistant', 'Помощник'),
  ('duration', 'Длительность'),
  ('change', 'Изменение'),
  ('media', 'СМИ'),
  ('real', 'Настоящий'),
  ('drawing', 'Рисунок'),
  ('prince', 'Принц'),
  ('on', 'На'),
  ('leadership', 'Руководство'),
  ('invitation', 'Приглашение'),
  ('Mr', 'Господин'),
  ('less', 'Меньше'),
  ('human', 'Человек'),
  ('collector', 'Собиратель'),
  ('otherwise', 'Иначе'),
  ('health', 'Здоровье'),
  ('within', 'Внутри'),
  ('I need', 'Мне нужно'),
  ('evidence', 'Доказательство'),
  ('above', 'Над'),
  ('century', 'Век'),
  ('tried to', 'Попытался'),
  ('death', 'Смерть'),
  ('external', 'Внешний'),
  ('return', 'Возврат'),
  ('body', 'Тело'),
  ('blood', 'Кровь'),
  ('access', 'Доступ'),
  ('cultural', 'Культурный'),
  ('half', 'Половина'),
  ('prevent', 'Предотвращать'),
  ('attach', 'Прикреплять'),
  ('believer', 'Верующий'),
  ('beautiful', 'Красивый'),
  ('always', 'Всегда'),
  ('known', 'Известный'),
  ('become', 'Стать'),
  ('rejection', 'Отказ'),
  ('girl', 'Девочка'),
  ('fire', 'Огонь'),
  ('production', 'Производство'),
  ('yesterday', 'Вчера'),
  ('week', 'Неделя'),
  ('writing', 'Письмо'),
  ('natural', 'Природный'),
  ('consider', 'Считать'),
  ('most important', 'Самый важный'),
  ('official', 'Чиновник'),
  ('father', 'Отец'),
  ('middle', 'Середина'),
  ('director', 'Директор'),
  ('defense', 'Оборона'),
  ('description', 'Описание'),
  ('followed', 'Следовал'),
  ('according to', 'Согласно'),
  ('financial', 'Финансовый'),
  ('forum', 'Форум'),
  ('need for', 'Необходимость'),
  ('may be', 'Может быть'),
  ('implementing', 'Реализация'),
  ('he asked', 'Спросил'),
  ('action', 'Действие'),
  ('providing', 'Предоставление'),
  ('contact', 'Контакт'),
  ('important', 'Важный'),
  ('oil', 'Нефть'),
  ('morning', 'Утро'),
  ('included', 'Включил'),
  ('poet', 'Поэт'),
  ('court', 'Суд'),
  ('Internet', 'Интернет'),
  ('chapter', 'Глава'),
  ('Jew', 'Еврей'),
  ('over', 'Над'),
  ('attempt', 'Попытка'),
  ('he told', 'Рассказал'),
  ('club', 'Клуб'),
  ('minimum', 'Минимум'),
  ('severe', 'Сильный'),
  ('meeting', 'Встреча'),
  ('safety', 'Безопасность'),
  ('just', 'Просто'),
  ('identifying', 'Определение'),
  ('local', 'Местный'),
  ('mind', 'Разум'),
  ('evil', 'Зло'),
  ('file', 'Файл'),
  ('fair', 'Справедливый'),
  ('called for', 'Призвал'),
  ('spending', 'Трата'),
  ('living', 'Жизнь'),
  ('street', 'Улица'),
  ('occupation', 'Оккупация'),
  ('die', 'Умереть'),
  ('gender', 'Пол'),
  ('list', 'Список'),
  ('twenty', 'Двадцать'),
  ('experience', 'Опыт'),
  ('or', 'Или'),
  ('ball', 'Мяч'),
  ('family', 'Семья'),
  ('literature', 'Литература'),
  ('future', 'Будущее'),
  ('status', 'Статус'),
  ('exposure', 'Воздействие'),
  ('civilian', 'Гражданский'),
  ('have been', 'Было'),
  ('origin', 'Происхождение'),
  ('dealing', 'Обращение'),
  ('wrong', 'Неправильный'),
  ('secret', 'Секрет'),
  ('higher', 'Выше'),
  ('doubt', 'Сомнение'),
  ('thought', 'Мысль'),
  ('pressure', 'Давление'),
  ('resident', 'Житель'),
  ('during', 'Во время'),
  ('hundred', 'Сто'),
  ('fourth', 'Четвёртый'),
  ('near', 'Близко'),
  ('usually', 'Обычно'),
  ('particular', 'Особый'),
  ('article', 'Статья'),
  ('against', 'Против'),
  ('bank', 'Банк'),
  ('organized', 'Организованный'),
  ('resistance', 'Сопротивление'),
  ('marriage', 'Брак'),
  ('degree', 'Степень'),
  ('popular', 'Популярный'),
  ('present', 'Настоящее'),
  ('size', 'Размер'),
  ('development', 'Развитие'),
  ('style', 'Стиль'),
  ('evening', 'Вечер'),
  ('he preferred', 'Предпочёл'),
  ('police', 'Полиция'),
  ('point', 'Точка'),
  ('planting', 'Посадка'),
  ('art', 'Искусство'),
  ('height', 'Высота'),
  ('joint', 'Совместный'),
  ('account', 'Счёт'),
  ('effect', 'Эффект'),
  ('south', 'Юг'),
  ('facing', 'Противостояние'),
  ('circumstance', 'Обстоятельство'),
  ('detail', 'Деталь'),
  ('most', 'Большинство'),
  ('nature', 'Природа'),
  ('together', 'Вместе'),
  ('revolution', 'Революция'),
  ('impact', 'Влияние'),
  ('only', 'Только'),
  ('send', 'Отправить'),
  ('completely', 'Полностью'),
  ('difficult', 'Трудный'),
  ('player', 'Игрок'),
  ('application', 'Приложение'),
  ('success', 'Успех'),
  ('difference', 'Разница'),
  ('visit', 'Визит'),
  ('provider', 'Поставщик'),
  ('color', 'Цвет'),
  ('necessary', 'Необходимый'),
  ('element', 'Элемент'),
  ('vision', 'Видение'),
  ('weapon', 'Оружие'),
  ('office', 'Офис'),
  ('suitable', 'Подходящий'),
  ('neighborhood', 'Район'),
  ('behind', 'Позади'),
  ('capable', 'Способный'),
  ('by', 'Через'),
  ('so', 'Итак'),
  ('investment', 'Инвестиция'),
  ('imam', 'Имам'),
  ('wish to', 'Желать'),
  ('launch', 'Запуск'),
  ('hope', 'Надежда'),
  ('treatment', 'Лечение'),
  ('effort', 'Усилие'),
  ('must be', 'Должно быть'),
  ('industry', 'Промышленность'),
  ('essential', 'Существенный'),
  ('initiated', 'Начал'),
  ('republic', 'Республика'),
  ('daily', 'Ежедневный'),
  ('nuclear', 'Ядерный'),
  ('direction', 'Направление'),
  ('agency', 'Агентство'),
  ('north', 'Север'),
  ('mosque', 'Мечеть'),
  ('thanks', 'Спасибо'),
  ('reform', 'Реформа'),
  ('logic', 'Логика'),
  ('step', 'Шаг'),
  ('business', 'Бизнес'),
  ('hit', 'Удар'),
  ('game', 'Игра'),
  ('children of Adam', 'Дети Адама'),
  ('sky', 'Небо'),
  ('journalist', 'Журналист'),
  ('presidency', 'Президентство'),
  ('charge', 'Обвинение'),
  ('almost', 'Почти'),
  ('dish', 'Блюдо'),
  ('concept', 'Концепция'),
  ('problem', 'Проблема')
) AS m(en, ru)
WHERE w.translation_ru = m.en;

-- Имена сподвижников в хадисах (если остались латинские варианты)
UPDATE public.hadiths SET author = replace(replace(replace(replace(author,
  'Abu Bakr', 'Абу Бакр (р.а.)'),
  'Uthman', 'Усман (р.а.)'),
  'Umar', 'Умар (р.а.)'),
  'Ali', 'Али (р.а.)')
WHERE author ~ '[A-Za-z]';
