-- Academy quizzes 4/5/6 with 60 unique questions
INSERT INTO quizzes (id, title, category, difficulty) OVERRIDING SYSTEM VALUE VALUES
  (4, 'Академия: Легко', 'Академия', 'easy'),
  (5, 'Академия: Средне', 'Академия', 'medium'),
  (6, 'Академия: Хардкор', 'Академия', 'hard')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, difficulty = EXCLUDED.difficulty;

SELECT setval(pg_get_serial_sequence('quizzes', 'id'), GREATEST((SELECT MAX(id) FROM quizzes), 6));

DELETE FROM questions WHERE quiz_id IN (4, 5, 6);

INSERT INTO questions (quiz_id, question_text, options, correct_option_index, xp_reward, coins_reward) VALUES
(4, 'Сколько столпов Ислама?', array['Три','Пять','Семь','Девять'], 1, 10, 5),
(4, 'Как называется ежедневная молитва?', array['Закят','Саум','Намаз','Хадж'], 2, 10, 5),
(4, 'В каком месяце пост Рамадан?', array['Шавваль','Рамадан','Раджаб','Мухаррам'], 1, 10, 5),
(4, 'Как называется свидетество веры?', array['Салят','Шахада','Закят','Саум'], 1, 10, 5),
(4, 'Сколько сур в Коране?', array['100','114','120','99'], 1, 10, 5),
(4, 'Как называется направление для молитвы?', array['Кибла','Михраб','Минбар','Муаззин'], 0, 10, 5),
(4, 'Кто был последним Пророком?', array['Иса (а.с.)','Муса (а.с.)','Мухаммад ﷺ','Ибрахим (а.с.)'], 2, 10, 5),
(4, 'Сколько раз в день обязательный намаз?', array['Три','Четыре','Пять','Шесть'], 2, 10, 5),
(4, 'Как называется пост?', array['Закят','Саум','Хадж','Итикаф'], 1, 10, 5),
(4, 'В каком городе родился Пророк ﷺ?', array['Медина','Мекка','Иерусалим','Дамаск'], 1, 10, 5),
(4, 'Как называется паломничество в Мекку?', array['Умра','Хадж','Итикаф','Таравих'], 1, 10, 5),
(4, 'Кто принёс первое откровение?', array['Микаил','Джибриль','Исрафил','Азраил'], 1, 10, 5),
(4, 'Как называется ежегодная милостыня?', array['Садака','Закят','Фитр','Хумс'], 1, 10, 5),
(4, 'Как называется священная книга мусульман?', array['Тора','Инджил','Коран','Псалтырь'], 2, 10, 5),
(4, 'Как называется молитва в пятницу?', array['Таравих','Джумуа','Витр','Тахаджjud'], 1, 10, 5),
(4, 'Сколько частей (джузов) в Коране?', array['20','30','40','114'], 1, 10, 5),
(4, 'Как называется малое паломничество?', array['Хадж','Умра','Итикаф','Саум'], 1, 10, 5),
(4, 'Кто первый пророк?', array['Нух','Адам (а.с.)','Идрис','Ибрахим'], 1, 10, 5),
(4, 'Как называется ночная молитва в Рамадан?', array['Витр','Таравих','Тахаджjud','Наfl'], 1, 10, 5),
(4, 'Как называется дом Аллаha в Мекке?', array['Мечеть','Кааба','Минaret','Михраб'], 1, 10, 5),
(5, 'Куда был перенесён Пророк ﷺ в ночь Исра?', array['Медина','Иерусалим','Мекка','Тайф'], 1, 15, 8),
(5, 'Как называлась первая мечеть в Исламе?', array['Аль-Акса','Куба','Ан-Нabawi','Каaba'], 1, 15, 8),
(5, 'Какая битва была первой?', array['Ухуд','Бадр','Хandaq','Хunayn'], 1, 15, 8),
(5, 'Кто был первым халифом?', array['Умар','Уthman','Абу Bakr','Ali'], 2, 15, 8),
(5, 'Кто составил Сахих al-Bukhari?', array['Мусlim','Аль-Bukhari','Ат-Tirmidhi','Ан-Nawawi'], 1, 15, 8),
(5, 'Сколько лет Пророк ﷺ пророчествовал?', array['10','13','23','40'], 2, 15, 8),
(5, 'Как называется год скорби?', array['Год слona','10-й год пророчества','Год слёз','2 AH'], 1, 15, 8),
(5, 'Кто была мать Пророка ﷺ?', array['Хadija','Амina','Fatima','Asiya'], 1, 15, 8),
(5, 'Кто был опекуном Пророка ﷺ?', array['Hamza','Abu Talib','Abbas','Abu Lahab'], 1, 15, 8),
(5, 'Как называется договор в Хudaybiya?', array['Constitution','Hudaybiya Treaty','Akaba','Badr'], 1, 15, 8),
(5, 'Кто первый муаззин?', array['Ali','Bilal','Umar','Abu Bakr'], 1, 15, 8),
(5, 'Какая сura без bismillah?', array['At-Tawba','Al-Fatiha','Al-Ikhlas','An-Nas'], 0, 15, 8),
(5, 'Сколько аятов в al-Fatiha?', array['5','6','7','8'], 2, 15, 8),
(5, 'Кто написал «Ar-Rahiq al-Makhtum»?', array['Ibn Kathir','Al-Mubarakpuri','As-Suyuti','At-Tabari'], 1, 15, 8),
(5, 'Как называется ночь al-Qadr?', array['15 Shaban','Laylat al-Qadr','Laylat al-Isra','Laylat al-Mi''raj'], 1, 15, 8),
(5, 'Кто была первая жена Пророка ﷺ?', array['Aisha','Khadija','Sawda','Hafsa'], 1, 15, 8),
(5, 'Хадис о намерениях — первый в?', array['Muslim','Bukhari','Muwatta','Tirmidhi'], 1, 15, 8),
(5, 'Сколько основных категорий hadith?', array['2','3','4','5'], 1, 15, 8),
(5, 'Кто был «вторым в пещере»?', array['Ali','Abu Bakr','Umar','Hamza'], 1, 15, 8),
(5, 'Как называется миграция в Медину?', array['Hijra','Isra','Hajj','Umrah'], 0, 15, 8),
(6, 'Сколько аятов в al-Baqara?', array['200','255','286','300'], 2, 25, 12),
(6, 'Кто составил «Muwatta»?', array['Malik ibn Anas','Al-Bukhari','Muslim','Ahmad ibn Hanbal'], 0, 25, 12),
(6, 'Какой год — «Год слона»?', array['Year of Elephant','Year of Sorrow','Year of Hijra','Year of Badr'], 0, 25, 12),
(6, 'Сколько мазhabов в суннитском fiqh?', array['2','3','4','5'], 2, 25, 12),
(6, 'Кто автор «Tafsir al-Jalalayn»?', array['Ibn Taymiyyah','Jalal ad-Din al-Mahalli','Al-Ghazali','Ibn Hazm'], 1, 25, 12),
(6, 'Как называется ayat an-Nur?', array['Ayat al-Kursi','Light verse','Throne verse','Last verse'], 1, 25, 12),
(6, 'Сколько дней основных rites Hajj?', array['3','5','7','10'], 1, 25, 12),
(6, 'Кто «Sayyid ash-Shuhada»?', array['Hamza','Ali','Umar','Uthman'], 0, 25, 12),
(6, 'Какая surah — «Umm al-Kitab»?', array['Al-Baqara','Al-Fatiha','Al-Ikhlas','Ya-Sin'], 1, 25, 12),
(6, 'Сколько juz в Коране?', array['20','30','40','114'], 1, 25, 12),
(6, 'Кто составил «Riyadh as-Salihin»?', array['An-Nawawi','Al-Bukhari','Ibn Majah','Ad-Daraqutni'], 0, 25, 12),
(6, 'Кто был «As-Siddiq»?', array['Umar','Abu Bakr','Ali','Uthman'], 1, 25, 12),
(6, 'Кто автор «Al-Adab al-Mufrad»?', array['Al-Bukhari','Muslim','Abu Dawud','At-Tirmidhi'], 0, 25, 12),
(6, 'В каком году был завоеван Мекka?', array['6 AH','8 AH','10 AH','2 AH'], 1, 25, 12),
(6, 'Сколько жён у Пророка ﷺ после Хadija (прибл.)?', array['5','9','13','15'], 2, 25, 12),
(6, 'Кто составил «Bulugh al-Maram»?', array['Ibn Hajar','Ibn Rajab','Al-Hafiz','Ibn Kathir'], 0, 25, 12),
(6, 'Какой месяц начинает исламский календарь?', array['Ramadan','Muharram','Rajab','Shawwal'], 1, 25, 12),
(6, 'Как называется surah Ya-Sin?', array['Heart of Quran','Throne','Light','Opening'], 0, 25, 12),
(6, 'Кто «Dhu an-Nun»?', array['Yunus','Musa','Isa','Ibrahim'], 0, 25, 12),
(6, 'Сколько times mentioned «Salat» in Quran (approx)?', array['50','100','150','200'], 1, 25, 12);
